name: Build

on:
  # These fields being blank makes it apply to all branches and PRs.
  push:
  pull_request:

jobs:
  build:
    # For future maintainers, taken from: https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/robot-code-ci.html
    # Check back there and compare if it doesn't work next year.
    runs-on: ubuntu-22.04
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile and run tests on robot code
      run: ./gradlew build